FROM eclipse-temurin:17-jdk

WORKDIR /app

COPY .mvn .mvn
COPY mvnw .
COPY pom.xml .

RUN chmod +x mvnw
RUN ./mvnw clean package -DskipTests

COPY src src

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "target/product-service-0.0.1-SNAPSHOT.jar"]